Numpy
Assignment Questions
Assignment Questions

1. What is a Python library? Why ^o we use Python libraries?
















ow can you generate a ran^om 3x3 matrix with values between 0 an^ 1?7. H


8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

 

9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A


12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

13.  What is the significance of the np.linalg.inv function?

14. What ^oes the np.reshape function ^o, an^ how is it use^?

15. What is broa^casting in Numpy?

Full Stack Data Science Pro

In [ ]:
'''1. What is a Python library?
    A Python library is a collection of related modules.
    It contains bundles of code that can be used repeatedly in different programs.
    Each module in a Python library serves a specific purpose.
    Libraries in Python are collections of precompiled codes that can be used later on in a 
    program for some specific well-defined operations¹. Other than pre-compiled codes, a library 
    may contain documentation, configuration data, message templates, classes, and values, etc.

2. Why do we use Python libraries?
    We use Python libraries to make programming simpler and more convenient. As we don’t need 
    to write the same code again and again for different programs, it helps in maintaining 
    the code’s modularity. Python libraries play a very vital role in fields of Machine Learning, 
    Data Science, Data Visualization, etc. They make using Python faster, more secure, and 
    compatible with other technologies because Python programmers don’t have to code everything 
    from scratch. Libraries may significantly speed up and simplify the process of writing and 
    completing jobs. Python is a popular choice for data analysis because of its extensive library of tools for manipulating, visualising,
    and training machine learning models.'''

In [ ]:

'''

2. What is the ^ifference between Numpy array an^ List?


1. Data Type:
   - Numpy Array: A Numpy array is homogeneous, meaning all elements must be of the same data type. This allows for more efficient storage and faster operations, especially for large data sets.
   - Python List: A Python list can hold items of different data types, including strings, integers, and even other lists. This flexibility can decrease memory efficiency and slow numerical operations.


2. Memory Efficiency:
   - Numpy Array: Numpy arrays are more memory-efficient than Python lists due to their homogeneous nature. They store data in contiguous blocks of memory, allowing for a more compact representation and faster access².
   - Python List: In a Python list, each item is an object that contains information about its data type and value, plus extra information like reference counters, which leads to higher memory overhead¹².

3. Performance:
   - Numpy Array: Numpy arrays generally offer superior speed compared to Python lists, especially for numerical operations on large data sets².
   - Python List: Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead¹.

4. Size Mutability:
   - Numpy Array: The size of a Numpy array is fixed. You can't change the size of a Numpy array without making a full copy.
   - Python List: Lists are dynamic and can be easily modified by adding, removing, or changing items².

5. Functionality:
   - Numpy Array: Numpy arrays come with a plethora of built-in functions that support high-level mathematical operations.
   - Python List: Lists are generally used as general-purpose data structures.

In summary, while Python lists are flexible and easy to use, Numpy arrays are more efficient and performant for numerical computations, especially with large datasets¹².



3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np 

arr=np.array(

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

)

print('shape of array ',arr.shape)
print('Size of array',arr.size)
print('Dimension of array',arr.ndim)

shape of array  (3, 4)
Size of array 12
Dimension of array 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
import numpy as np 

arr1=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
print('first row in array',arr1[0])

first row in array [1 2 3 4]


5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
import numpy as np 

arr=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

elements_of_array=arr[2,3]#this represent third row and 4th column
print('Elements of third and 4th column are',elements_of_array)


Elements of third and 4th row are 12


6. Write co^e to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

<!-- ad=[0,1,2,3,4,5,6,7,8,9]
print(ad[1::2]) -->

In [28]:
import numpy as np

arr=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

indexex_elements=arr[0::2,1::2]#here [0::(to-jump)2 steps]
print('all odd indexed elements are',indexex_elements)

all odd indexed elements are [[ 2  4]
 [10 12]]


7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [38]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix=np.random.uniform(0,1,size=(3,3))
print('random intergrs bw 0, 1  are \n',random_matrix)


random intergrs bw 0, 1  are 
 [[0.60922762 0.27160697 0.89253521]
 [0.90736931 0.59149745 0.9724845 ]
 [0.54853525 0.05035871 0.38184293]]


8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
'''
1. np.random.rand
   - `np.random.rand` generates random values in a given shape.
   - It creates an array of the given shape and populates it with random samples from a uniform distribution 
   over [0, 1).
   - The values are uniformly distributed over the interval [0, 1).

2. np.random.randn:
   - np.random.randn` generates samples from the "standard normal" distribution¹.
   - If positive, int-like arguments are provided, `randn` generates an array of shape 
   (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) 
   distribution of mean 0 and variance 1.
   - A single float randomly sampled from the distribution is returned if no argument is provided.
   

The main difference between them is the probabilistic distribution each number is drawn from. `np.random.rand` draws from a uniform distribution, 
while `np.random.randn` draws from a normal (Gaussian) distribution¹⁴. This difference can have significant effects when these functions are used in applications like neural network weight initialization¹. For example, weights initialized with a normal distribution (via `np.random.randn`) can often lead to better model performance compared to weights initialized with a uniform distribution (via `np.random.rand`)¹.


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [41]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase the dimension of the array
arr_expanded = np.expand_dims(arr, axis=0)

print("Expanded array shape: ", arr_expanded.shape)


Expanded array shape:  (1, 3, 4)


: 

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
import numpy as np 

arr=np.array(

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

arr_transposed=np.transpose(arr)
print('Transposed array using np.transpose\n',arr_transposed)

#using T attribute
arr_transposed1=arr.T 
print('Transposed array using np.transpose1\n',arr_transposed1)


Transposed array using np.transpose
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Transposed array using np.transpose1
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consi^er the following matrix:

A2= [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

B2= [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:






12.	Which function in Numpy con be used to swop the byte order of on array?
13.	What is the significance of the np.IinoIg.inv function?
14.	What does the np.reshape function do, and how is it used?
15.	What is broadcasting in Numpy?


1.	Index wise multiplication

In [11]:
import numpy as np 

A2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

B2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

index_multiplication=np.multiply(A2,B2)
print('Result of index multiplication\n',index_multiplication)

Result of index multiplication
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


2.	Matrix multiplication

In [25]:
import numpy as np 

A2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

B2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

#as here tha matrix is 3,4 x 3,4--No. of col in A == No. row of B..So we have to transpose one of the matrix

transposed_B=np.transpose(B2)

matrix_multiplication_dot=np.dot(A2,transposed_B)

print('Result of matrix multiplication using dot\n',matrix_multiplication_dot)

transposed_B=np.transpose(B2)
matrix_multiplication_matmul=np.matmul(A2,transposed_B)

print('Result of matrix multiplication using matmul function \n',matrix_multiplication_matmul)

Result of matrix multiplication using dot
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Result of matrix multiplication using matmul function 
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


3.	Add both the metrics

In [38]:
import numpy as np 

A2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

B2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

matrix_add=np.add(A2,B2)
print('Result of added matrix\n',matrix_add)

Result of added matrix
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


4.	Subtract matrix B from A

In [39]:
import numpy as np 

A2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

B2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

matrix_sub=np.subtract(A2,B2)
print('Result of index subtraction\n',matrix_sub)
print('another method is use operatior - \n',B2-A2)

Result of index subtraction
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
another method is use operatior - 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


5.	Divide Matrix B by A

In [41]:
import numpy as np 

A2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

B2= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

matrix_div=np.divide(A2,B2)
print('Result of index multiplication\n',matrix_div)

Result of index multiplication
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12.	Which function in Numpy con be used to swop the byte order of on array?

In Numpy, you can use [ ndarray.byteswap()] funtion to swap the byte order from the array. This function toggles between low-eng to big-end data repesentation by returning the byteswapped array.

In [59]:
import numpy as np 

arr=np.array([1,30,500,2000,142324],dtype=np.int16)
print(arr.byteswap(inplace=True))

[   256   7680  -3071 -12281  -3029]


C:\Users\ravit\AppData\Local\Temp\ipykernel_30776\1733906402.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 142324 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr=np.array([1,30,500,2000,142324],dtype=np.int16)


13.	What is the significance of the np.IinoIg.inv function?

The [np.linalg.inv] function in Numpy is used to compute the (multiplicative) inverse of a square matrix. 

Multiplicative inverse is such that if the orignal matrix is multiplied with multiplicative inverse it results in identitiy matrix.

Let us prove this below:

In [87]:
import numpy as np 

a=np.array([[1,2],[8,9]])

multiplicative_invese=np.linalg.inv(a)

print('This is multiplicative inverse\n',abs(multiplicative_invese))
identity=np.multiply(a,multiplicative_invese)
print('Proof of identity matrix after multiplying orignal with multiplicative inverse\n',
abs(identity))

This is multiplicative inverse
 [[1.28571429 0.28571429]
 [1.14285714 0.14285714]]
Proof of identity matrix after multiplying orignal with multiplicative inverse
 [[1.28571429 0.57142857]
 [9.14285714 1.28571429]]


14.	What does the np.reshape function do, and how is it used?

The [np.reshape()] function is used to change the shape of the array without modifying its data.

In [90]:
import numpy as np 

#this is 1d array
arrd=np.array([1,2,4,6,7,8,9,0,7])

# Lets change to 2d array :: Logic to be followed numpy.reshape(a, newshape, order='C')

arr2d=np.reshape(arrd,(3,3))
print('after reshaping',arr2d)



after reshaping [[1 2 4]
 [6 7 8]
 [9 0 7]]
